# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7773a57f934dbd5fc019487bf4827d796bcde9238d1145dd4ea0546c3bf2204e18972aaa9d6b1544b0a1c1122fcdcb01f3c25f48c6087697e163e133218b15f

test:
  secret_key_base: 3997f7116569a73e93a5653b8988f78342e2a9fbb0e9711aa87ed72222192406227acd3be905043058a74503e6663f5aa6c00e98109cc6ddcf58fba76620d0d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
